image: artifactory.quanti.cz/docker/node-yarn-awscli:18

variables:
  CHANNEL: "#pin_deployment"
  USERNAME: "PIN Deploy"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - .yarn

stages:
 - lint
 - build
 - deploy_dev
 - deploy_test
 - deploy_stage
 - deploy_demo
 - deploy_prod

.deploy:
  before_script:
    - aws configure set aws_access_key_id ${aws_access_key_id}
    - aws configure set aws_secret_access_key ${aws_secret_access_key}
    - aws configure set default.region eu-central-1
  script:
    - yarn install
    - ./ci/report-slack.sh start ${ENV}
    - ./ci/get-info.sh
    - ./ci/build-deploy.sh ${ENV}
  after_script:
    - ./ci/report-slack.sh ${CI_JOB_STATUS} ${ENV}

lint:
  stage: lint
  # variables:
  #   NODE_OPTIONS: --max-old-space-size=4096
  before_script:
    - yarn install
  script:
    - yarn lint
  except:
    - tags

build:
  stage: build
  variables:
    NODE_OPTIONS: --max-old-space-size=4096
  before_script:
    - yarn install
  script:
    - yarn build
  except:
    - tags

deploy dev1:
  stage: deploy_dev
  environment:
    name: dev1
    url: https://dev1.humansis.org
  variables:
    ENV: dev1
  extends: .deploy
  only:
    - branches
  when: manual

deploy dev2:
  stage: deploy_dev
  environment:
    name: dev2
    url: https://dev2.humansis.org
  variables:
    ENV: dev2
  extends: .deploy
  only:
    - branches
  when: manual

deploy dev3:
  stage: deploy_dev
  environment:
    name: dev3
    url: https://dev3.humansis.org
  variables:
    ENV: dev3
  extends: .deploy
  only:
    - branches
  when: manual

deploy test:
  stage: deploy_test
  environment:
    name: test
    url: https://test.humansis.org
  variables:
    ENV: test
  extends: .deploy
  only:
    - branches
  when: manual

deploy stage:
  stage: deploy_stage
  environment:
    name: stage
    url: https://stage.humansis.org
  variables:
    ENV: stage
  extends: .deploy
  only:
    - /^release\/.*$/
  except:
    - tags

deploy stage2:
  stage: deploy_stage
  environment:
    name: stage2
    url: https://stage2.humansis.org
  variables:
    ENV: stage2
  extends: .deploy
  only:
    - /^release\/.*$/
  except:
    - tags
  when: manual

deploy prod:
  stage: deploy_prod
  environment:
    name: production
    url: https://pin.humansis.org
  variables:
    ENV: production
  extends: .deploy
  only:
    - /^v.*$/
  except:
    - branches
  when: manual
  allow_failure: false

deploy demo:
  stage: deploy_demo
  environment:
    name: demo
    url: https://demo.humansis.org
  variables:
    ENV: demo
  extends: .deploy
  only:
    - /^v.*$/
    - /^release\/.*$/
  when: manual
