version: '3.1'

volumes:
  node_modules:

services:

  web:
    build:
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

    ports:
      - 8080:8080
    command: sh -c "yarn install  && yarn run build  && http-server dist"

