export default {
	APP_LOADING: "APP_LOADING",
	CHANGE_COUNTRY: "CHANGE_COUNTRY",
	CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
	SET_PERMISSIONS: "SET_PERMISSIONS",
	UPDATE_PER_PAGE: "UPDATE_PER_PAGE",
	LOGIN_SUCCEEDED: "LOGIN_SUCCEEDED",
	LOGOUT: "LOGOUT",
	LOAD_ICONS: "LOAD_ICONS",
};
