export default {
	CHANGE_COUNTRY: "",
	CHANGE_LANGUAGE: "",
	SET_PERMISSIONS: "",
	UPDATE_ASSISTANCE: "",
	UPDATE_PROJECT: "",
	UPDATE_PER_PAGE: "",
	LOGIN_SUCCEEDED: "LOGIN_SUCCEEDED",
	LOGOUT: "LOGOUT",
};
