export default {
	// MUTATIONS
	APP_LOADING: "APP_LOADING",
	STORE_COUNTRIES: "STORE_COUNTRIES",
	STORE_COUNTRY: "STORE_COUNTRY",
	STORE_LANGUAGE: "STORE_LANGUAGE",
	STORE_TRANSLATIONS: "STORE_TRANSLATIONS",
	STORE_USER: "STORE_USER",
	STORE_PERMISSIONS: "STORE_PERMISSIONS",
	STORE_PER_PAGE: "STORE_PER_PAGE",
	STORE_ICONS: "STORE_ICONS",
	LOGOUT: "LOGOUT",

	// CODE LIST for PERMISSIONS
	PERMISSIONS: [
		{ key: "ADD_PROJECT", value: "addProject" },
		{ key: "EDIT_PROJECT", value: "editProject" },
		{ key: "DELETE_PROJECT", value: "deleteProject" },
		{ key: "VIEW_PROJECT", value: "viewProject" },
		{ key: "ADD_DISTRIBUTION", value: "addDistribution" },
		{ key: "EDIT_DISTRIBUTION", value: "editDistribution" },
		{ key: "DELETE_DISTRIBUTION", value: "deleteDistribution" },
		{ key: "VIEW_DISTRIBUTION", value: "viewDistribution" },
		{ key: "ASSIGN_DISTRIBUTION_ITEMS", value: "assignDistributionItems" },
		{ key: "ADD_BENEFICIARY", value: "addBeneficiary" },
		{ key: "EDIT_BENEFICIARY", value: "editBeneficiary" },
		{ key: "DELETE_BENEFICIARY", value: "deleteBeneficiary" },
		{ key: "VIEW_BENEFICIARY", value: "viewBeneficiary" },
		{ key: "IMPORT_BENEFICIARIES", value: "importBeneficiaries" },
		{ key: "EXPORT_BENEFICIARIES", value: "exportBeneficiaries" },
		{ key: "VIEW_VOUCHERS", value: "viewVouchers" },
		{ key: "EXPORT_OR_PRINT_VOUCHERS", value: "exportOrPrintVouchers" },
		{ key: "ADD_VOUCHERS", value: "addVouchers" },
		{ key: "VIEW_VENDORS", value: "viewVendors" },
		{ key: "ADD_OR_EDIT_VENDORS", value: "addOrEditVendors" },
		{ key: "VIEW_DONORS", value: "viewDonors" },
		{ key: "ADD_OR_EDIT_DONORS", value: "addOrEditDonors" },
		{ key: "VIEW_PRODUCTS", value: "viewProducts" },
		{ key: "ADD_OR_EDIT_PRODUCTS", value: "addOrEditProducts" },
		{ key: "COUNTRY_REPORT", value: "countryReport" },
		{ key: "PROJECT_REPORT", value: "projectReport" },
		{ key: "DISTRIBUTION_REPORT", value: "distributionReport" },
		{ key: "AUTHORISE_ELECTRONIC_CASH_TRANSFER", value: "authoriseElectronicCashTransfer" },
		{ key: "COUNTRY_SETTINGS", value: "countrySettings" },
		{ key: "ADD_OR_EDIT_USERS", value: "addOrEditUsers" },
		{ key: "ADMIN_SETTINGS", value: "adminSettings" },
	],
};
