export default {
	STATUS: {
		CREATING: "creating",
		NEW: "new",
		VALIDATED: "validated",
		CLOSED: "closed",
	},
	DEFAULT_SELECTED_STATUS: ["creating", "new", "validated"],
	DEFAULT_SELECTED_STATUS_BUTTONS: {
		creating: true,
		new: true,
		validated: true,
		closed: false,
	},
	TARGET: {
		INDIVIDUAL: "individual",
		HOUSEHOLD: "household",
		INSTITUTION: "institution",
	},
	TYPE: {
		ACTIVITY: "activity",
		DISTRIBUTION: "distribution",
	},
	CRITERIA_TARGET: {
		HEAD: "Head",
		BENEFICIARY: "Beneficiary",
		HOUSEHOLD: "Household",
	},
	CRITERIA: {
		HAS_VALID_SMART_CARD: "hasValidSmartcard",
	},
	CRITERIA_FIELD_TYPE: {
		CORE: "core",
		CUSTOM: "custom",
	},
	COMPONENT: {
		SELECTION_CRITERIA: "selectionCriteria",
		DISTRIBUTED_COMMODITY: "distributedCommodity",
		INSTITUTIONS: "institutions",
		ACTIVITY_DESCRIPTION: "activityDescription",
		HOUSEHOLD_TARGETED: "householdsTargeted",
		INDIVIDUALS_TARGETED: "individualsTargeted",
	},
	DEFAULT_FORM_MODEL: {
		modality: null,
		modalityType: null,
		division: null,
		unit: null,
		quantity: null,
		value: null,
		currency: null,
		secondUnit: null,
		secondQuantity: null,
		description: null,
		payloadDivisionNwsFields: [
			{
				rangeFrom: 1,
				rangeTo: 1,
				value: null,
			},
			{
				rangeFrom: 2,
				rangeTo: 2,
				value: null,
			},
			{
				rangeFrom: 3,
				rangeTo: 3,
				value: null,
			},
			{
				rangeFrom: 4,
				rangeTo: 4,
				value: null,
			},
			{
				rangeFrom: 5,
				rangeTo: null,
				value: null,
			},
		],
		payloadDivisionNesFields: [
			{
				rangeFrom: 1,
				rangeTo: 3,
				value: null,
			},
			{
				rangeFrom: 4,
				rangeTo: 6,
				value: null,
			},
			{
				rangeFrom: 7,
				rangeTo: 9,
				value: null,
			},
			{
				rangeFrom: 10,
				rangeTo: null,
				value: null,
			},
		],
		payloadDivisionCodLimitedFields: [
			{
				rangeFrom: 1,
				rangeTo: 3,
				value: null,
			},
			{
				rangeFrom: 4,
				rangeTo: null,
				value: null,
			},
		],
		payloadDivisionCodExpandedFields: [
			{
				rangeFrom: 1,
				rangeTo: 3,
				value: null,
			},
			{
				rangeFrom: 4,
				rangeTo: 5,
				value: null,
			},
			{
				rangeFrom: 6,
				rangeTo: 9,
				value: null,
			},
			{
				rangeFrom: 10,
				rangeTo: null,
				value: null,
			},
		],
		remoteDistributionAllowed: false,
		allowedProductCategoryTypes: [],
		cashbackLimit: null,
	},
	DEFAULT_DISPLAYED_FIELDS: {
		division: false,
		unit: false,
		quantity: false,
		value: false,
		currency: false,
		secondUnit: false,
		secondQuantity: false,
		description: false,
		customField: false,
		amountMultiplier: false,
		remoteDistributionAllowed: false,
		allowedProductCategoryTypes: false,
		householdMembersNwsFields: false,
		householdMembersNesFields: false,
		householdMembersCodLimitedFields: false,
		householdMembersCodExpandedFields: false,
		dateExpiration: false,
	},
	MODALITY: {
		CASH: "Cash",
		VOUCHER: "Voucher",
		IN_KIND: "In Kind",
		OTHER: "Other",
	},
	COMMODITY: {
		CASH: "Cash",
		MOBILE_MONEY: "Mobile Money",
		SMARTCARD: "Smartcard",
		FOOD_RATIONS: "Food Rations",
		READY_TO_EAT_RATIONS: "Ready to Eat Rations",
		BREAD: "Bread",
		AGRICULTURAL_KIT: "Agricultural Kit",
		WASH_KIT: "WASH Kit",
		SHELTER_TOOL_KIT: "Shelter tool kit",
		HYGIENE_KIT: "Hygiene kit",
		DIGNITY_KIT: "Dignity kit",
		NFI_KIT: "NFI Kit",
		WINTERIZATION_KIT: "Winterization Kit",
		ACTIVITY_ITEM: "Activity item",
		LOAN: "Loan",
		BUSINESS_GRANT: "Business Grant",
		QR_CODE_VOUCHER: "QR Code Voucher",
		PAPER_VOUCHER: "Paper Voucher",
		CASHBACK: "Cashback",
		DISTRIBUTION: {
			PER_HOUSEHOLD: "Per Household",
			PER_INDIVIDUAL: "Per Individual",
			PER_CUSTOM_AMOUNT_BY_CUSTOM_FIELD: "Per Custom Amount By Custom Field",
			PER_MEMBERS_CODE: "Per Household Members",
			PER_MEMBER: {
				CODE: "Per Household Member",
				LABEL: "Per Member (uniformly)",
			},
			PER_MEMBERS_NWS: {
				CODE: "Per Members NWS",
				LABEL: "Per Members NWS (1, 2, 3, 4, 5+)",
			},
			PER_MEMBERS_NES: {
				CODE: "Per Members NES",
				LABEL: "Per Members NES (1-3, 4-6, 7-9, 10+)",
			},
			PER_MEMBERS_COD_LIMITED: {
				CODE: "Per Members COD Limited",
				LABEL: "Per Members COD (1-3, 4+)",
			},
			PER_MEMBERS_COD_EXPANDED: {
				CODE: "Per Members COD Expanded",
				LABEL: "Per Members COD (1-3, 4-5, 6-9, 10+)",
			},
		},
	},
	FIELD_TYPE: {
		GENDER: "gender",
		DATE: "date",
		RESIDENCY_STATUS: "residencyStatus",
		BOOLEAN: "boolean",
		LIVELIHOOD: "livelihood",
		DOUBLE: "double",
		INTEGER: "integer",
		LOCATION: "location",
		LOCATION_TYPE: "locationType",
		STRING: "string",
		ARRAY: "array",
	},
	ROUNDS_OPTIONS: [{ code: null, value: "N/A" }]
		.concat(
			Array.from(Array(100).keys()).slice(1, 100).map((num) => ({ code: num, value: num })),
		),
	INPUT_DISTRIBUTED: {
		IDS_LIST_MAX_LENGTH: 5000,
		DEFAULT_FORM_MODEL: {
			idType: null,
			idsList: "",
			justification: "",
		},
	},
	INTEGRITY_ISSUES: {
		HOUSEHOLD_WITHOUT_HEAD: "Household without head",
	},
	SEARCH_FIELDS: [
		{ code: "beneficiaryId", value: "BNF ID" },
		{ code: "familyName", value: "Local family name" },
		{ code: "nationalId", value: "ID Number" },
	],
	RELIEF_PACKAGES: {
		STATE: {
			DISTRIBUTED: "Distributed",
			TO_DISTRIBUTED: "To distributed",
			INVALIDATED: "Invalidated",
			CANCELED: "Canceled",
		},
	},
};
