export default {
	DEFAULT_FORM_MODEL: {
		institutionName: "",
		institutionType: "",
		projectName: "",
		addressStreet: "",
		addressNumber: "",
		addressPostCode: "",
		longitude: null,
		latitude: null,
		contactGivenName: "",
		contactParentsName: "",
		contactFamilyName: "",
		nationalCardType: "",
		nationalCardNumber: "",
		otherContactInformation: "",
		externalReceivedTypes: "",
		supportDateReceived: null,
		supportOrganization: "",
		note: "",
		eloNumber: null,
		contractNumber: null,
		adm1: null,
		adm2: null,
		adm3: null,
		adm4: null,
		phone1: {
			type: "",
			proxy: false,
			ext: "",
			phoneNo: "",
		},
		phone2: {
			type: "",
			proxy: false,
			ext: "",
			phoneNo: "",
		},
		firstInstitutionId: "",
		secondInstitutionId: "",
		thirdInstitutionId: "",
	},
};
