const DEFAULT_FILTERS = {
	INVOICING: null,
	DATE_FROM: null,
	DATE_TO: null,
	GENDER: null,
	LOCATIONS: [],
	PROJECTS: [],
	VENDORS: [],
	COMMODITY: [],
	ASSISTANCES: [],
	BENEFICIARIES: [],
	MODALITY_TYPES: [],
	VULNERABILITIES: [],
	BENEFICIARY_TYPES: [],
	RESIDENCY_STATUSES: [],
	REFERRAL_TYPES: [],
	LIVELIHOODS: [],
	CURRENCIES: [],
	STATUS: [],
	STATUSES: [],
	ADM1: [],
	ADM2: [],
	ADM3: [],
	ADM4: [],
};

export default {
	DEFAULT_FILTERS,
};
