export default {
	STATE: {
		INTEGRITY_CHECKING: "Integrity Checking",
		IDENTITY_CHECKING: "Identity Checking",
		SIMILARITY_CHECKING: "Similarity Checking",
		FINISHED: "Finished",
		CANCELED: "Canceled",
		IMPORTING: "Importing",
	},
	STATUS: {
		NEW: "New",
		UPDATING: "UPDATING",
		UPLOADING: "Uploading",
		INTEGRITY_CHECK: "Integrity Checking",
		INTEGRITY_CHECK_CORRECT: "Integrity Check Correct",
		INTEGRITY_CHECK_FAILED: "Integrity Check Failed",
		IDENTITY_CHECK: "Identity Checking",
		IDENTITY_CHECK_CORRECT: "Identity Check Correct",
		IDENTITY_CHECK_FAILED: "Identity Check Failed",
		SIMILARITY_CHECK: "Similarity Checking",
		SIMILARITY_CHECK_CORRECT: "Similarity Check Correct",
		SIMILARITY_CHECK_FAILED: "Similarity Check Failed",
		FINISH: "Finished",
		CANCEL: "Canceled",
		IMPORTING: "Importing",
	},
	ITEM_STATUS: {
		TO_CREATE: "To Create",
		TO_UPDAT: "To Update",
		TO_LINK: "To Link",
		TO_IGNORE: "To Ignore",
	},
	ITEM_STATE: {
		DUPLICITY_KEEP_THEIRS: "Duplicity Keep Theirs",
		DUPLICITY_KEEP_OURS: "Duplicity Keep Ours",
	},
};
