const ADMIN = "ROLE_ADMIN";
const FIELD_OFFICER = "ROLE_FIELD_OFFICER";
const PROJECT_OFFICER = "ROLE_PROJECT_OFFICER";
const PROJECT_MANAGER = "ROLE_PROJECT_MANAGER";
const COUNTRY_MANAGER = "ROLE_COUNTRY_MANAGER";
const REGIONAL_MANAGER = "ROLE_REGIONAL_MANAGER";
const ENUMERATOR = "ROLE_ENUMERATOR";

export default {
	ADMIN,
	FIELD_OFFICER,
	PROJECT_OFFICER,
	PROJECT_MANAGER,
	COUNTRY_MANAGER,
	REGIONAL_MANAGER,
	ENUMERATOR,
};
