export default {
	ADMIN: "ROLE_ADMIN",
	GUEST: "ROLE_GUEST",
	FIELD_OFFICER: "ROLE_FIELD_OFFICER",
	PROJECT_OFFICER: "ROLE_PROJECT_OFFICER",
	PROJECT_MANAGER: "ROLE_PROJECT_MANAGER",
	COUNTRY_MANAGER: "ROLE_COUNTRY_MANAGER",
	REGIONAL_MANAGER: "ROLE_REGIONAL_MANAGER",
	ENUMERATOR: "ROLE_ENUMERATOR",
};
