export default {
	ROUTE_NAME: {
		ROOT: "dashboard",
		LOGIN: "login",
		LOGOUT: "logout",
		ACCOUNT_CREATED: "accountCreated",
		NO_PERMISSION: "noPermission",
		NO_COUNTRY_ASSIGNED: "noCountryAssigned",
		NOT_FOUND: "notFound",
		HOME: "home",
		HOUSEHOLD_INFORMATION_SUMMARY: "householdInformationSummary",
		VENDORS: "vendors",
		VOUCHERS: "vouchers",
		COUNTRY_SETTINGS: "countrySettings",
		PRODUCTS: "products",
		COUNTRY_SPECIFICS: "countrySpecifics",
		ADMINISTRATIVE_SETTINGS: "administrativeSettings",
		DONORS: "donors",
		MY_ORGANIZATIONS: "myOrganizations",
		ORGANIZATION_SERVICES: "organizationServices",
		SYNC: "sync",
		PROFILE: "profile",
		PROJECTS: {
			ROOT: "projects",
			ADD: "addProject",
			DETAIL: "projectDetail",
			EDIT: "projectEdit",
		},
		ASSISTANCES: {
			ROOT: "project",
			ADD: "addAssistance",
			EDIT: "assistanceEdit",
			DETAIL: "assistanceDetail",
			CREATION_PROGRESS: "assistanceCreationProgress",
		},
		IMPORTS: {
			ROOT: "imports",
			NEW: "import",
		},
		HOUSEHOLDS: {
			ROOT: "households",
			ADD: "addHousehold",
			EDIT: "editHousehold",
		},
		INSTITUTIONS: {
			ROOT: "institutions",
			ADD: "addInstitution",
			DETAIL: "institutionDetail",
			EDIT: "institutionEdit",
		},
		USERS: {
			ROOT: "users",
			ADD: "addUser",
			DETAIL: "userDetail",
			EDIT: "userEdit",
		},
		ROLES: {
			ROOT: "roles",
			ADD: "addRole",
			DETAIL: "roleDetail",
			EDIT: "roleEdit",
		},
		TRANSACTIONS: {
			ROOT: "transactions",
			ASSISTANCES: "transactionsAssistances",
			PURCHASES: "transactionsPurchases",
		},
	},
};
