export default {
	PER_PAGE_OPTIONS: [10, 20, 50, 100],
	DEFAULT_SORT_OPTIONS: {
		ASSISTANCES: { key: "dateDistribution", order: "desc" },
		ASSISTANCE_EDIT: {
			HOUSEHOLD: { key: "createdAt", order: "asc" },
			INSTITUTION: { key: "createdAt", order: "asc" },
		},
		ASSISTANCE_LIST: { key: "dateDistribution", order: "desc" },
		CUSTOM_FIELDS: { key: "id", order: "asc" },
		DISTRIBUTIONS: { key: "dateDistribution", order: "desc" },
		DONORS: { key: "fullname", order: "asc" },
		HOUSEHOLDS: { key: "createdAt", order: "asc" },
		IMPORTS: { key: "createdAt", order: "desc" },
		INSTITUTIONS: { key: "createdAt", order: "asc" },
		PRODUCTS_CATEGORIES: { key: "id", order: "asc" },
		PRODUCTS_ITEMS: { key: "id", order: "asc" },
		PROJECTS: { key: "endDate", order: "desc" },
		PURCHASE_LIST: { key: "datePurchase", order: "desc" },
		SMARTCARD_PURCHASED: { key: "datePurchase", order: "desc" },
		USERS: { key: "id", order: "desc" },
		VENDORS: { key: "id", order: "asc" },
		VOUCHERS: { key: "code", order: "desc" },
	},
};
